version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080 # for jenkins web interface
      - 50000:50000 # for jenkins slave agents (runners)
    container_name: jenkins-tp02
    volumes:
      - "D:/Devops/TP2/jenkins_agents_home:/var/jenkins_home"
    links:
      - "laravel-agent:laravel"

  laravel-agent:
    build: ./laravel-agent
    image: TP2/jenkins-agent:latest
    container_name: jenkins-laravel-agent-TP2
    environment:
      - JENKINS_URL=http://localhost:8080
      - JENKINS_AGENT_NAME=laravel-agent-TP2
      - JENKINS_AGENT_SSH_PUBKEY=your_secret_here # replace with your actual SSH public key
